{% set name = "featuremap-learn" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/featuremap-learn-{{ version }}.tar.gz
  sha256: 4ce6ed6d7c7f015bf2d5eb4a6e9d53655ae9ded74d16d3419e7c5a892bea6550

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.13
    - scikit-learn >=0.16
    - scipy >=0.19
    - numba >=0.55.0
    - umap-learn >=0.5.1

test:
  imports:
    - featuremap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/YYT1002/FeatureMAP
  summary: FeatureMAP
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HongjianSun
